apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-broker.fullname" . }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kafka-broker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kafka-broker.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kafka-broker.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9092
              protocol: TCP
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: {{ default "9092" .Values.kafkaenv.KAFKA_ADVERTISED_PORT | quote}}
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: {{ default "127.0.0.1" .Values.kafkaenv.KAFKA_ADVERTISED_HOST_NAME | quote}}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ default "127.0.0.1:2181" .Values.kafkaenv.KAFKA_ZOOKEEPER_CONNECT | quote}}
            - name: KAFKA_BROKER_ID
              value: {{ default "0" .Values.kafkaenv.KAFKA_BROKER_ID | quote}}
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
