apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-svc-np
  labels:
    name: kafka
    id: "1"
spec:
  type: NodePort
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      nodePort: 30702
      protocol: TCP
  selector:
    app: kafka
    id: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-svc-cip
  labels:
    name: kafka
    id: "1"
spec:
  type: ClusterIP
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
    id: "1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-1-pv-claim
  labels:
    app: kafka
    id: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "1"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "30702"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 192.168.0.15
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zoo1:2181
            - name: KAFKA_BROKER_ID
              value: "1"
          volumeMounts:
            - name: kafka-1-broker-logs
              mountPath: /kafka
      volumes:
        - name: kafka-1-broker-logs
          persistentVolumeClaim:
            claimName: kafka-broker-1-pv-claim